# See documentation at https://goreleaser.com/customization/build.
project_name: webrpc

builds:
  - main: ./cmd/webrpc-gen
    binary: webrpc-gen
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/webrpc/webrpc/gen.VERSION=v{{.Version}}
  - main: ./cmd/webrpc-test
    binary: webrpc-test
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/webrpc/webrpc/gen.VERSION=v{{.Version}}

archives:
  - name_template: "{{ .Binary }}.{{ .Os }}-{{ .Arch }}"
    format: binary

checksum:
  name_template: "checksums.txt"

release:
  footer: |
    ## Docker
    ```
    docker run ghcr.io/webrpc/webrpc-gen:v{{.Version}}
    ```

    ## Homebrew
    ```
    brew tap webrpc/tap
    brew install webrpc-gen
    ```

    ## Build from source
    ```
    go install -ldflags="-s -w -X github.com/webrpc/webrpc/gen.VERSION=v{{.Version}}" github.com/webrpc/webrpc/cmd/webrpc-gen@v{{.Version}}
    ```

    ## Download binaries
    macOS: [amd64](https://github.com/webrpc/webrpc/releases/download/v{{.Version}}/webrpc-gen.darwin-amd64), [arm64](https://github.com/webrpc/webrpc/releases/download/v{{.Version}}/webrpc-gen.darwin-arm64) (Apple Silicon)
    Linux: [amd64](https://github.com/webrpc/webrpc/releases/download/v{{.Version}}/webrpc-gen.linux-amd64), [arm64](https://github.com/webrpc/webrpc/releases/download/v{{.Version}}/webrpc-gen.linux-arm64)
    Windows: [amd64](https://github.com/webrpc/webrpc/releases/download/v{{.Version}}/webrpc-gen.windows-amd64.exe), [arm64](https://github.com/webrpc/webrpc/releases/download/v{{.Version}}/webrpc-gen.windows-arm64.exe)

changelog:
  use: github
  sort: asc

brews:
  - name: webrpc-gen
    tap:
      owner: webrpc
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/webrpc/webrpc"
    description: "generate source code for your target language from webrpc schema"
    license: "MIT"
